server:
  port: 9005

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: solus19910808
    url: jdbc:mysql://47.94.18.61:9001/purchase_record?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false



mybatis:
  mapper-locations: classpath:mapper/*.xml
